# Generated by Django 6.0.4 on 2026-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='mode',
            field=models.CharField(choices=[('standard', '일반 추출'), ('ai', 'AI 추출')], default='standard', max_length=10),
        ),
    ]
